# Generated by Django 5.2.17 on 2026-09-25 23:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='締め日')),
                ('budget', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='上限金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '期間',
                'verbose_name_plural': '期間',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='period_end_date_gte_start_date'), models.CheckConstraint(condition=models.Q(('budget__gte', 1)), name='period_budget_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='品名')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='金額')),
                ('purchased_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='購入日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.period', verbose_name='期間')),
            ],
            options={
                'verbose_name': '支出',
                'verbose_name_plural': '支出',
                'ordering': ['-purchased_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 1)), name='expense_amount_gte_1')],
            },
        ),
    ]
