# Generated by Django 5.2.17 on 2026-09-27 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='utf8mb4_bin', max_length=20, unique=True, verbose_name='カテゴリ名')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', '色は #RRGGBB の形式で指定してください。')], verbose_name='色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.category', verbose_name='カテゴリ'),
        ),
    ]
